# Generated by Django 3.2.7 on 2021-10-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Обшая цена')),
                ('total_quantity', models.PositiveIntegerField(default=1, verbose_name='Обшая колличество')),
                ('product_list', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='carts.cart')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
